/**
 * Typed DOM lookups. Every client script goes through these.
 *
 * Why they exist: this TypeScript program contains both `lib.dom` and the
 * workerd runtime types generated by `wrangler types`. Both declare `Element`,
 * so the two declarations merge - and workerd's HTMLRewriter members
 * (`remove(): Element`, `append(content, options): Element`) clash with the
 * DOM's (`remove(): void`, `append(...nodes): void`). The merged `Element`
 * then satisfies neither side, which poisons everything built on it:
 * `HTMLElement`, `ParentNode`, and therefore the constraints on
 * `querySelector<T>`, `querySelectorAll<T>` and `closest<T>`.
 *
 * Method calls still work fine at runtime and in the checker - only
 * *assignability* between the merged types fails. So these helpers take
 * unconstrained type parameters and a structural `Queryable`, never naming a
 * poisoned type, and cast at the boundary. Callers get precise element types
 * and none of the noise.
 *
 * `HTMLElement` is fine as a type *default* - defaults are not checked
 * against a constraint - so untyped calls still get sensible inference.
 *
 * The alternative would be hand-writing the `Env` interface to keep the
 * runtime types out, which this project has deliberately rejected: bindings
 * come from `wrangler types` so they cannot drift from wrangler.jsonc.
 * Containing the fallout in one small module is the cheaper side of that trade.
 */

/** Structural stand-in for `ParentNode`, which the merge above makes unusable. */
interface Queryable {
  querySelector(selectors: string): unknown;
  querySelectorAll(selectors: string): ArrayLike<unknown>;
}

export function qs<T = HTMLElement>(selector: string, root: Queryable = document): T | null {
  return (root.querySelector(selector) as T | null) ?? null;
}

/** For elements the page is known to contain - throws rather than failing obscurely later. */
export function must<T = HTMLElement>(selector: string, root: Queryable = document): T {
  const found = qs<T>(selector, root);
  if (found === null) throw new Error(`Expected an element matching ${selector}`);
  return found;
}

export function qsa<T = HTMLElement>(selector: string, root: Queryable = document): T[] {
  return Array.from(root.querySelectorAll(selector)) as T[];
}

/** `closest` from an event target, guarding the non-element cases callers always face. */
export function closest<T = HTMLElement>(from: unknown, selector: string): T | null {
  if (from === null || typeof from !== "object" || !("closest" in from)) return null;
  const node = from as { closest(selectors: string): unknown };
  return (node.closest(selector) as T | null) ?? null;
}
